name: Build LibrimeKit
on:
  workflow_dispatch:
  push:
    # branches:
      # - main
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore Cache Boost
        id: cache-boost-restore
        uses: actions/cache@v4
        with:
          path: |
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/frameworks
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/dest
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/scripts
          key: ${{ runner.os }}-boost

      - name: Build Boost
        if: (steps.cache-boost-restore.outputs.cache-hit != 'true')
        run: |
          make boost-build

      - name: copy Boost
        if: (steps.cache-boost-restore.outputs.cache-hit == 'true')
        run: |
          make boost-copy
      
      - name: Save Cache Boost
        id: cache-boost-save
        uses: actions/cache@v4
        with:
          path: |
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/frameworks
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/dest
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/scripts
          key: ${{ runner.os }}-boost

      - name: Build Librime
        run: |
          make librime-build

      - name: Make Archive
        run: |
          tar -acf Frameworks.tgz Frameworks

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          name: librimekit-frameworks
          path: Frameworks.tgz

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: Frameworks.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

